### ISSUE TITLE
[MAJOR] Environment Variables Cleanup and Documentation

### ISSUE THREAD

**Issue by abebeos** [abebeos/agoric-sdk#7]
(early draft)

## Related Main Issue
- https://github.com/Agoric/agoric-sdk/issues/3581

## Tasks / Issues

- [ ] List/Document all env-vars in one document
- [ ] Categorize the env-vars ("good/keep", "bad/remove", "strange/redesign")
  - [ ] File Actionable Issues 

## Re existent Issue:

- [ ] Process https://github.com/Agoric/agoric-sdk/issues/3581
  - what has been achieved? (Issue text should be updated)
  - what is still relevant in the comments? (resolved comments should be collapsed)
  - what further steps need to be taken? (should be filed in sub-issues)
